### ISSUE TITLE
Package upgrade hangs as long as service is running

### ISSUE THREAD

**Issue by klyonrad** [chef-cookbooks/mysql#481] opened 2016-09-29 12:58 UTC
### Cookbook version

7.2.0
### Chef-client version

12.9.41
### Platform Details

Ubuntu 14
### Scenario:

Minor version Upgrade the `mysql-server`
### Steps to Reproduce:

install an older package version by provisioning with the following configuration:

``` ruby
mysql_service 'default' do
  instance 'default'
  bind_address node['mysql']['bind_address']
  port node['mysql']['port']
  version '5.5'
  package_version '5.5.35+dfsg-1ubuntu1'
  package_action :install
  error_log '/var/log/mysql/error.log'
  socket '/var/run/mysqld/mysqld.sock' unless node['platform_version'].to_f >= 16.04
  pid_file '/var/run/mysqld/mysqld.pid' unless node['platform_version'].to_f >= 16.04
  action [:create, :start]
end
```

and after provisioning delete `package_version` line and set `package_action :upgrade` (or run `aptitude upgrade mysql-server-5.5`
### Expected Result:

A successfull package upgrade run for mysql-server package.
### Actual Result:

The upgrade process hangs. Upgrading only works when the process is stopped manually (`service mysql-default stop`).

The same behaviour can be observed by bumping the `package_version` between to chef-client runs

**Comment by klyonrad** [comment] 2016-10-05 12:34
When updating, the debian `postinst` script attempts to shutdown the `mysql` service
http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/mysql-5.5/trusty-updates/view/head:/debian/mysql-server-5.5.postinst#L63
`set +e; invoke stop; set -e`

calling stop on the `mysql` service does not work because this cookbook configures that service to be stopped / not running

```shell
service mysql stop

stop: Unknown instance: 
```

**Comment by cheeseplus** [comment] 2017-04-05 22:39
Labeling this as a bug for now but this will probably end up a dupe as it's related to some other core architectural issues of how the cookbook is structured.

**Comment by cheeseplus** [comment] 2017-04-05 22:41
Dupe of https://github.com/chef-cookbooks/mysql/issues/466

**Closed by cheeseplus** 2017-04-05 22:41 UTC
Labels: Type: Bug
