### ISSUE TITLE
Ubuntu 14.04 Mysql 5.6 not working on cookbook 6.0

### ISSUE THREAD

**Issue by christopher5106** [chef-cookbooks/mysql#331] opened 2015-04-24 09:33 UTC
Here is the issue : install not working (apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 )

==> default: [2015-04-24T09:22:55+00:00] INFO: file[/var/lib/apt/periodic/update-success-stamp] updated atime and mtime to 2015-04-24 09:22:55 +0000
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local] created directory /var/cache/local
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local] owner changed to 0
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local] group changed to 0
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local] mode changed to 755
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local/preseeding] owner changed to 0
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local/preseeding] group changed to 0
==> default: [2015-04-24T09:22:55+00:00] INFO: directory[/var/cache/local/preseeding] mode changed to 755
==> default: [2015-04-24T09:24:03+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-04-24T09:24:03+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-04-24T09:24:03+00:00] ERROR: Running exception handlers
==> default: [2015-04-24T09:24:03+00:00] ERROR: Exception handlers complete
==> default: [2015-04-24T09:24:03+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-04-24T09:24:03+00:00] ERROR: mysql_service[default] (mysql2::default line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: package[default :create mysql-server-5.6] (/tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service.rb line 32) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl libmysqlclient18
==> default:   libterm-readkey-perl mysql-client-5.6 mysql-client-core-5.6 mysql-common
==> default:   mysql-common-5.6 mysql-server-core-5.6
==> default: Suggested packages:
==> default:   libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
==> default:   libsql-statement-perl libipc-sharedcache-perl mailx tinyca
==> default: The following NEW packages will be installed:
==> default:   libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl libmysqlclient18
==> default:   libterm-readkey-perl mysql-client-5.6 mysql-client-core-5.6 mysql-common
==> default:   mysql-common-5.6 mysql-server-5.6 mysql-server-core-5.6
==> default: 0 upgraded, 12 newly installed, 0 to remove and 99 not upgraded.
==> default: Need to get 21.5 MB of archives.
==> default: After this operation, 165 MB of additional disk space will be used.
==> default: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libaio1 amd64 0.3.109-4 [6364 B]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-common all 5.5.43-0ubuntu0.14.04.1 [13.8 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libmysqlclient18 amd64 5.5.43-0ubuntu0.14.04.1 [596 kB]
==> default: Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libdbi-perl amd64 1.630-1 [879 kB]
==> default: Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main libdbd-mysql-perl amd64 4.025-1 [99.3 kB]
==> default: Get:6 http://archive.ubuntu.com/ubuntu/ trusty/main libterm-readkey-perl amd64 2.31-1 [27.4 kB]
==> default: Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe mysql-client-core-5.6 amd64 5.6.19-0ubuntu0.14.04.1 [4081 kB]
==> default: Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe mysql-client-5.6 amd64 5.6.19-0ubuntu0.14.04.1 [5526 kB]
==> default: Get:9 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe mysql-server-core-5.6 amd64 5.6.19-0ubuntu0.14.04.1 [4761 kB]
==> default: Get:10 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe mysql-server-5.6 amd64 5.6.19-0ubuntu0.14.04.1 [5452 kB]
==> default: Get:11 http://archive.ubuntu.com/ubuntu/ trusty/main libhtml-template-perl all 2.95-1 [65.5 kB]
==> default: Get:12 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe mysql-common-5.6 all 5.6.19-0ubuntu0.14.04.1 [15.0 kB]
==> default: Preconfiguring packages ...
==> default: Fetched 21.5 MB in 12s (1764 kB/s)
==> default: Selecting previously unselected package libaio1:amd64.
==> default: (Reading database ... 62823 files and directories currently installed.)
==> default: Preparing to unpack .../libaio1_0.3.109-4_amd64.deb ...
==> default: Unpacking libaio1:amd64 (0.3.109-4) ...
==> default: Selecting previously unselected package mysql-common.
==> default: Preparing to unpack .../mysql-common_5.5.43-0ubuntu0.14.04.1_all.deb ...
==> default: Unpacking mysql-common (5.5.43-0ubuntu0.14.04.1) ...
==> default: Selecting previously unselected package libmysqlclient18:amd64.
==> default: Preparing to unpack .../libmysqlclient18_5.5.43-0ubuntu0.14.04.1_amd64.deb ...
==> default: Unpacking libmysqlclient18:amd64 (5.5.43-0ubuntu0.14.04.1) ...
==> default: Selecting previously unselected package libdbi-perl.
==> default: Preparing to unpack .../libdbi-perl_1.630-1_amd64.deb ...
==> default: Unpacking libdbi-perl (1.630-1) ...
==> default: Selecting previously unselected package libdbd-mysql-perl.
==> default: Preparing to unpack .../libdbd-mysql-perl_4.025-1_amd64.deb ...
==> default: Unpacking libdbd-mysql-perl (4.025-1) ...
==> default: Selecting previously unselected package libterm-readkey-perl.
==> default: Preparing to unpack .../libterm-readkey-perl_2.31-1_amd64.deb ...
==> default: Unpacking libterm-readkey-perl (2.31-1) ...
==> default: Selecting previously unselected package mysql-client-core-5.6.
==> default: Preparing to unpack .../mysql-client-core-5.6_5.6.19-0ubuntu0.14.04.1_amd64.deb ...
==> default: Unpacking mysql-client-core-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Selecting previously unselected package mysql-client-5.6.
==> default: Preparing to unpack .../mysql-client-5.6_5.6.19-0ubuntu0.14.04.1_amd64.deb ...
==> default: Unpacking mysql-client-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Selecting previously unselected package mysql-server-core-5.6.
==> default: Preparing to unpack .../mysql-server-core-5.6_5.6.19-0ubuntu0.14.04.1_amd64.deb ...
==> default: Unpacking mysql-server-core-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Setting up mysql-common (5.5.43-0ubuntu0.14.04.1) ...
==> default: Selecting previously unselected package mysql-server-5.6.
==> default: (Reading database ... 63195 files and directories currently installed.)
==> default: Preparing to unpack .../mysql-server-5.6_5.6.19-0ubuntu0.14.04.1_amd64.deb ...
==> default: Unpacking mysql-server-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Selecting previously unselected package libhtml-template-perl.
==> default: Preparing to unpack .../libhtml-template-perl_2.95-1_all.deb ...
==> default: Unpacking libhtml-template-perl (2.95-1) ...
==> default: Selecting previously unselected package mysql-common-5.6.
==> default: Preparing to unpack .../mysql-common-5.6_5.6.19-0ubuntu0.14.04.1_all.deb ...
==> default: Unpacking mysql-common-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Setting up libaio1:amd64 (0.3.109-4) ...
==> default: Setting up libmysqlclient18:amd64 (5.5.43-0ubuntu0.14.04.1) ...
==> default: Setting up libdbi-perl (1.630-1) ...
==> default: Setting up libdbd-mysql-perl (4.025-1) ...
==> default: Setting up libterm-readkey-perl (2.31-1) ...
==> default: Setting up mysql-client-core-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Setting up mysql-client-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Setting up mysql-server-core-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Setting up mysql-server-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Setting up libhtml-template-perl (2.95-1) ...
==> default: Setting up mysql-common-5.6 (5.6.19-0ubuntu0.14.04.1) ...
==> default: Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: STDERR: start: Job failed to start
==> default: invoke-rc.d: initscript mysql, action "start" failed.
==> default: dpkg: error processing package mysql-server-5.6 (--configure):
==> default:  subprocess installed post-installation script returned error exit status 1
==> default: Errors were encountered while processing:
==> default:  mysql-server-5.6
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: ---- End output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 returned 100
==> default: 
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql2/recipes/default.rb
==> default: 
==> default:   1: mysql_service 'default' do
==> default:   2:   port '3306'
==> default:   3:   version '5.6'
==> default:   4:   initial_root_password node.mysql[:server_root_password]
==> default:   5:   action [:create, :start]
==> default:   6: end
==> default:   7: 
==> default: 
==> default: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql2/recipes/default.rb:1:in `from_file'
==> default: 
==> default: mysql_service("default") do
==> default:   action [:create, :start]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   cookbook_name :mysql2
==> default:   recipe_name "default"
==> default:   port "3306"
==> default:   version "5.6"
==> default:   initial_root_password "hsqru9Yj"
==> default:   package_action :install
==> default:   instance "default"
==> default:   run_user "mysql"
==> default:   run_group "mysql"
==> default: end
==> default: 
==> default: 
==> default: 
==> default: [2015-04-24T09:22:29+00:00] INFO: Forking chef instance to converge...
==> default: [2015-04-24T09:24:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by someara** [comment] 2015-04-24 12:26
I can't seem to duplicate this... just did a test-kitchen run and everything seems fine from a fresh install.

https://gist.github.com/someara/6413ce914c4edc4c938d

From your output:
==> default: invoke-rc.d: initscript mysql, action "start" failed.

Do you have something running on the machine that might cause the debian packaging post-installation scripts to fail?

**Comment by christopher5106** [comment] 2015-04-24 12:31
I just have these cookbooks prior to it : 

"recipe[git]","recipe[apt]","recipe[ark]",

cookbook 'apt', git: 'git://github.com/opscode-cookbooks/apt.git'
cookbook 'ark',  git: 'git://github.com/opscode-cookbooks/ark.git'

git is from Supermarket

The VM is   config.vm.box = "ubuntu/trusty64"

**Comment by aarsan** [comment] 2015-06-07 19:04
I'm having the same problem. Seems to work fine with 5.5.

**Comment by someara** [comment] 2015-06-15 00:05
I can't reproduce this...

Here is my test-kitchen output: https://gist.github.com/someara/d162292b87785fcd97fb

Oddly enough, #335 says 5.5 is broken but 5.6 works, 
Oddly enough, #331 says 5.6 is broken but 5.5 works.

I suspect you need to increase the ram in your VM.

Closing for now, please re-open if that doesn't fix it.

**Closed by someara** 2015-06-15 00:05 UTC

**Comment by yarivdev** [comment] 2015-09-30 09:37
apt is asking whether to override the config file, which makes the recipe crash.
To reproduce, install on a fresh ubuntu 14.04(64) with defaults, then update recipe to include:
```
version '5.6'
```
run chef and behold:

```
      Configuration file '/etc/init/mysql.conf'
       ==> Modified (by you or by a script) since installation.
       ==> Package distributor has shipped an updated version.
         What would you like to do about it ?  Your options are:
          Y or I  : install the package maintainer's version
          N or O  : keep your currently-installed version
            D     : show the differences between the versions
            Z     : start a shell to examine the situation
       The default action is to keep your current version.
      *** mysql.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package mysql-server-5.6 (--configure):
       EOF on stdin at conffile prompt
      Errors were encountered while processing:
       mysql-server-5.6
      E: Sub-process /usr/bin/dpkg returned an error code (1)
      ---- End output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
      Ran apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 returned 100
```

Thanks for this great work btw.
