### ISSUE TITLE
ERROR -- : Actor crashed! Encoding::InvalidByteSequenceError: "\xE2" on US-ASCII

### ISSUE THREAD

**Issue by eriksenonline** [chef-cookbooks/mysql#279] opened 2015-01-13 10:37 UTC
When I try to run berks install with my cookbook I get an issue for one of the depended cookbooks.
I use the latest Chef DK client and use the DK enviroment as my default ruby.

Fetching cookbook index from https://supermarket.getchef.com...
Installing apt (2.6.1)
Installing hostsfile (2.4.5)
Installing ntp (1.7.0)
Installing smf (2.2.1)
Installing mysql (6.0.6)
Installing cron (1.6.1)
Installing rbac (1.0.2)
Using superkul_base (0.1.0) from source at ../superkul_base
Using superkul_simple-lamp (0.1.0) from source at .
Installing system (0.3.3)
Installing yum (3.5.2)
Installing yum-mysql-community (0.1.11)
E, [2015-01-13T11:34:13.430919 #3902] ERROR -- : Actor crashed!
Encoding::InvalidByteSequenceError: "\xE2" on US-ASCII
	/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode'
	/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
	/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `new'
	/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `parse'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.0/lib/ridley/chef/cookbook/metadata.rb:458:in `from_json'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.0/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.0/lib/ridley/chef/cookbook.rb:36:in `from_path'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:86:in `cookbook'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:67:in `import'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:30:in `import'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:106:in `block in install'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:38:in `block in download'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `download'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
/opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `new'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/json/common.rb:155:in `parse'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.0/lib/ridley/chef/cookbook/metadata.rb:458:in `from_json'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.0/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.0/lib/ridley/chef/cookbook.rb:36:in `from_path'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:86:in `cookbook'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:67:in `import'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:30:in `import'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:106:in `block in install'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:38:in `block in download'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `download'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:104:in `value'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:68:in `value'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:175:in `map'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:175:in `install_from_universe'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:39:in `run'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:370:in `install'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:143:in `install'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
	from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
	from /opt/chefdk/bin/berks:38:in `load'
	from /opt/chefdk/bin/berks:38:in `<main>'

**Comment by someara** [comment] 2015-01-13 21:43
This smells like a Chef / ChefDK bug to me...
At first glance, it looks like its choking on yum-mysql-community... 
At second glance, I can't reproduce this at all on either cookbook.

Can you put the exact version of your OS, ChefDK, etc in here so we can gather more info?

**Comment by someara** [comment] 2015-01-16 22:12
Cannot reproduce.. closing for now.

**Closed by someara** 2015-01-16 22:12 UTC
