### ISSUE TITLE
Can't change mysql root password with recipe.

### ISSUE THREAD

**Issue by chris-fa** [chef-cookbooks/mysql#483] opened 2016-10-19 23:06 UTC
### Cookbook version

8.0
### Chef-client version

12.13.37
### Platform Details

Centos 6
### Scenario:

Change root password for mysql
### Steps to Reproduce:
1. Define an `msyql_service` resource with `initial_root_password` from an attribute
2. Run Chef to provision
3. Change said attribute's value
4. Re-run chef to re-provision
### Expected Result:

I'm able to log in with the new password.
### Actual Result:

Root account still uses the password from the first provision

**Comment by klyonrad** [comment] 2016-10-20 11:29
This is more like a feature request. As the name suggests `initial_root_password` is an **initial** value and only used when mysql gets initialized. You can work around that by storing the root password somewhere else and trigger an PW update when that is changed.

**Comment by chris-fa** [comment] 2016-10-20 12:57
Is there any resource in the cookbook I can use to do that PW update, or should I do it with a command?

**Comment by klyonrad** [comment] 2016-11-18 11:06
no, you have to execute the password change with your own MySQL script

**Comment by cheeseplus** [comment] 2016-12-23 06:06
As explained this is working as intended so I'm closing this out.

**Closed by cheeseplus** 2016-12-23 06:06 UTC
