### ISSUE TITLE
systemd mysql-default-wait-ready does not handle inital startup of mysqld

### ISSUE THREAD

**Issue by vpal** [chef-cookbooks/mysql#512] opened 2017-02-23 11:59 UTC
### Cookbook version
8.2.0

### Chef-client version
12.18.31

### Platform Details
Ubuntu 16.04

### Scenario:
Create a new mysql instance fails because it seems that mysqld is doing some initialization on first startup which likely takes some time and does not open the socket before this is ready.
Because of this mysql-default-wait-ready kills it immediately.
Script output with set -x on inital startup:
```
+ daemon_pid=27285
+ ret=0
+ /bin/true
+ /usr/bin/mysqladmin --no-defaults --socket=/run/mysql-default/mysqld.sock --user=UNKNOWN_MYSQL_USER ping
+ RESPONSE=mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/run/mysql-default/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/run/mysql-default/mysqld.sock' exists!
+ mret=1
+ [ 1 -eq 0 ]
+ [ 1 -ne 1 -a 1 -ne 11 ]
+ grep -q Access denied for user
+ echo mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/run/mysql-default/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/run/mysql-default/mysqld.sock' exists!
+ /bin/kill -0 27285
+ ret=1
+ break
+ exit 1
```
Same initial startup with a `sleep 10` at the beginning of the script:
```
+ daemon_pid=28842
+ sleep 10
+ ret=0
+ /bin/true
+ /usr/bin/mysqladmin --no-defaults --socket=/run/mysql-default/mysqld.sock --user=UNKNOWN_MYSQL_USER ping
+ RESPONSE=mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'UNKNOWN_MYSQL_USER'@'localhost' (using password: NO)'
+ mret=0
+ [ 0 -eq 0 ]
+ break
+ exit 0
```

### Steps to Reproduce:
Simple service like this does the job :
```
mysql_service 'default' do
  port '3306'
  version node['mysql']['version']
  initial_root_password root_password
  action :create
end
```
`systemctl stop mysql-default.service; rm -rf /var/lib/mysql-data/mysql-default /var/log/mysql-default /etc/mysql-default; chef-client`

### Expected Result:
MySQL daemon initial startup should not fail.

### Actual Result:
Initial startup fails.

`/usr/share/mysql/mysql-systemd-start` from the Ubuntu  MySQL package seem to be a proper implementation of the same functionality.

**Comment by iennae** [comment] 2017-03-01 07:00
I am unable to replicate this issue using test kitchen on my local development station with the example you've given.

`/usr/share/mysql/mysql-systemd-start` appears to wait approximately 30 seconds with for i in $(seq 1 30) while mysqld-wait-ready will wait indefinitely. I'm not sure how you are running into the situation where it's dying. 

On initialization depending on the size of the data directory the process could take a while to get ready. Do you have an extremely large data directory?

**Comment by vpal** [comment] 2017-03-12 16:17
Hi @iennae. No there is no user generated data in MySQL when this happens, the only difference from a standard setup is that the MySQL data directory is on an encrypted disk.
It is actually the first startup after instance creation that is initiated by the recipe itself when the service fails to start. The only data in the data directory is what was generated by by the recipe itself during instance creation time data directory initialization. If that first startup is done the systemd scripts in the recipe seem to work okay.

I'm not able to do additional tests with this right now unfortunately as I already deleted that node and went with another solution. I could try to reproduce this and gather additional details later if needed.

I'm not using this cookbook right now because of other issues, so if I'm the only one facing this issue or if you are unable to reproduce this please feel free to cancel/ignore this issue.

**Comment by iennae** [comment] 2017-03-13 04:54
Ahh. If you do come back to this and find that you can replicate this with more information, I'd be happy to help debug. As I can't reproduce at this time, I'm going to go ahead and close this for now. Thanks so much for getting back to me.

**Closed by iennae** 2017-03-13 04:54 UTC
Labels: Status: Pending Contributor Response
