### ISSUE TITLE
Mysql fails to start due to: `/usr/libexec/mysqld: Can't find file: './mysql/plugin.frm' (errno: 13)`

### ISSUE THREAD

**Issue by marcoamorales** [chef-cookbooks/mysql#332] opened 2015-04-24 21:25 UTC
Hello! I created a simple test cookbook to replicate this issue that occurs in Centos 6.6:

```
mysql_service 'default' do
  action [:create, :start]
end

mysql_client 'default'
```

Error message from chef:
```
================================================================================
             Error executing action `start` on resource 'service[default :start mysql-default]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of /sbin/service mysql-default start ----
             STDOUT: Starting MySQL instance mysql-default
             Starting mysql-default:  [FAILED]
             STDERR: 
             ---- End output of /sbin/service mysql-default start ----
             Ran /sbin/service mysql-default start returned 1
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cookbooks/mysql/libraries/provider_mysql_service_sysvinit.rb
             
       26:           service "#{new_resource.name} :start #{mysql_name}" do
       27:             service_name mysql_name
       28:             provider Chef::Provider::Service::Init::Redhat if node['platform_family'] == 'redhat'
       29:             provider Chef::Provider::Service::Init::Insserv if node['platform_family'] == 'debian'
       30:             supports restart: true, status: true
       31:             action [:enable, :start]
       32:           end
       33:         end
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cookbooks/mysql/libraries/provider_mysql_service_sysvinit.rb:26:in `block in <class:Sysvinit>'
             
             service("default :start mysql-default") do
        action [:enable, :start]
        updated true
        supports {:restart=>true, :status=>true}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "mysql-default"
        enabled true
        pattern "default :start mysql-default"
        declared_type :service
        cookbook_name :"mysql-test"
             end
             
           
           ================================================================================
           Error executing action `start` on resource 'mysql_service[default]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           service[default :start mysql-default] (/tmp/kitchen/cookbooks/mysql/libraries/provider_mysql_service_sysvinit.rb line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service mysql-default start ----
           STDOUT: Starting MySQL instance mysql-default
           Starting mysql-default:  [FAILED]
           STDERR: 
           ---- End output of /sbin/service mysql-default start ----
           Ran /sbin/service mysql-default start returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/mysql-test/recipes/default.rb
           
             9: mysql_service 'default' do
            10:   action [:create, :start]
            11: end
            12: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/mysql-test/recipes/default.rb:9:in `from_file'
           
           mysql_service("default") do
             action [:create, :start]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :mysql_service
             cookbook_name :"mysql-test"
             recipe_name "default"
             package_action :install
             instance "default"
             run_user "mysql"
             run_group "mysql"
             initial_root_password "ilikerandompasswords"
             charset "utf8"
             port "3306"
           end
           
       
       Running handlers:
       [2015-04-24T21:17:22+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-04-24T21:17:22+00:00] ERROR: Exception handlers complete
       [2015-04-24T21:17:22+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 13 resources updated in 63.052236317 seconds
       [2015-04-24T21:17:22+00:00] ERROR: mysql_service[default] (mysql-test::default line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: service[default :start mysql-default] (/tmp/kitchen/cookbooks/mysql/libraries/provider_mysql_service_sysvinit.rb line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /sbin/service mysql-default start ----
       STDOUT: Starting MySQL instance mysql-default
       Starting mysql-default:  [FAILED]
       STDERR: 
       ---- End output of /sbin/service mysql-default start ----
       Ran /sbin/service mysql-default start returned 1
       [2015-04-24T21:17:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

This is what the `error.log` looks like:

```
[root@default-centos-66 ~]# cat /var/log/mysql-default/error.log 
150424 21:16:46 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql-default
150424 21:16:46  InnoDB: Initializing buffer pool, size = 8.0M
150424 21:16:46  InnoDB: Completed initialization of buffer pool
InnoDB: The first specified data file ./ibdata1 did not exist:
InnoDB: a new database to be created!
150424 21:16:46  InnoDB: Setting file ./ibdata1 size to 10 MB
InnoDB: Database physically writes the file full: wait...
150424 21:16:46  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile0 size to 5 MB
InnoDB: Database physically writes the file full: wait...
150424 21:16:46  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
150424 21:16:46  InnoDB: Started; log sequence number 0 0
150424 21:16:46 [Note] Event Scheduler: Loaded 0 events
150424 21:16:46 [Note] /usr/libexec/mysqld: ready for connections.
Version: '5.1.73'  socket: '/var/run/mysql-default/mysqld.sock'  port: 3306  Source distribution
150424 21:16:47 [Note] /usr/libexec/mysqld: Normal shutdown

150424 21:16:47 [Note] Event Scheduler: Purging the queue. 0 events
150424 21:16:47  InnoDB: Starting shutdown...
150424 21:16:51  InnoDB: Shutdown completed; log sequence number 0 44233
150424 21:16:51 [Note] /usr/libexec/mysqld: Shutdown complete

150424 21:16:51 mysqld_safe mysqld from pid file /var/run/mysql-default/mysqld.pid ended
150424 21:16:52 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql-default
/usr/libexec/mysqld: Can't find file: './mysql/plugin.frm' (errno: 13)
150424 21:16:52 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
150424 21:16:52  InnoDB: Initializing buffer pool, size = 8.0M
150424 21:16:52  InnoDB: Completed initialization of buffer pool
150424 21:16:52  InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to
InnoDB: the directory.
InnoDB: File name ./ibdata1
InnoDB: File operation call: 'open'.
InnoDB: Cannot continue operation.
150424 21:16:52 mysqld_safe mysqld from pid file /var/run/mysql-default/mysqld.pid ended
```

This was done in a simple cookbook with just that one recipe and no other recipes/dependencies other than mysql cookbook 6.0.21.

**Comment by schwing** [comment] 2015-04-29 21:30
Can you run `getenforce` on that instance? I'm thinking it's SELinux.

**Comment by marcoamorales** [comment] 2015-05-01 18:23
Looks like indeed SELinux is the culprit

```
[root@default-centos-66 ~]# ls -lZ /var/lib
...
drwxr-xr-x. mysql   mysql system_u:object_r:mysqld_db_t:s0 mysql
drwxr-x---. mysql   mysql unconfined_u:object_r:var_lib_t:s0 mysql-default
```

**Comment by mstyne** [comment] 2015-05-15 19:47
Is changing the context for this directory something we can hope to see added to the `mysql` cookbook, or should those brave few that leave SELinux enabled handle it in our own deployment routines? I can confirm that:

`chcon -Rv --type=mysqld_db_t /var/lib/mysql-default`

does the trick and allows MySQL to start.

**Comment by brandocorp** [comment] 2015-05-18 19:30
I just ran into this issue, and ended up pointing my data_dir attribute at `/var/lib/mysql` since I only needed one instance. This is a quick and dirty fix. 

I found [this](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Managing_Confined_Services/sect-Managing_Confined_Services-MySQL-Configuration_Examples.html) documentation to be helpful.

**Comment by someara** [comment] 2015-06-14 23:53
Glad you tracked this down. SELinux strikes again. Closing.

**Closed by someara** 2015-06-14 23:53 UTC
